### ISSUE TITLE
Backgrund color is still black

### ISSUE THREAD

**Issue by MatPitt** [DevBlooming/jetbrains-fleet-one-dark-theme#2]
Hi, I love this theme. I used it on a different computer and now while setting up in a new device, I followed the steps on the read me but it doesnt like quite like in the screenshot, it seems to only impact words color and not background colors as it remains like black. Any ideas what might be the issue here or something that I can try? thanks. 
<img width="1332" alt="Captura de pantalla 2024-08-14 a la(s) 1 21 51 a  m" src="https://github.com/user-attachments/assets/eeaf8bc5-4692-4a02-b103-4b878a2c06e4">
Attached is a screenshot of what it looks like

**Comment by MohamedIO** [comment]
Hi @MatPitt,
Sorry for late response. just put theme json file in this path `C:\users\<USER>\AppData\Roaming\JetBrains\Fleet\themes`.
i hope this will fix the problem.

**Comment by MatPitt** [comment]
Would it work on MacOS? is it a similar path to linux? Thanks Mohamed

**Comment by MohamedIO** [comment]
**Linux:** `/home/<USER>/.config/JetBrains/Fleet/themes/`

 **macOS:** `~/Library/Application Support/Jetbrains/Fleet/themes/`
